Rename make_package.sh without .sh extension

diff --git a/devtools/make_package b/devtools/make_package
--- a/devtools/make_package
+++ b/devtools/make_package
@@ -13,6 +13,10 @@ function make_python_package() {
 	cd ${BASEDIR}/${directory}
 	echo "Building python wheel ${name}"
 	python setup.py bdist_wheel --universal --dist-dir ${DISTDIR}
+	if [[ $? -ne 0 ]]; then
+		echo "Error building python wheel package ${name} : $?"
+		exit $?
+	fi
 }
 
 
